/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projetoindividual;

import java.util.Random;

/**
 *
 * @author IsabellaMaia
 */
public class proj2 extends javax.swing.JFrame {

    /**
     * Creates new form proj2
     */
    public proj2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        disco = new javax.swing.JLabel();
        cpu = new javax.swing.JLabel();
        memoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Disco");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 70, 50, 23);

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("CPU");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 70, 50, 23);

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Memória");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 70, 90, 23);

        calcular.setBackground(new java.awt.Color(255, 102, 102));
        calcular.setFont(new java.awt.Font("Dubai Light", 1, 15)); // NOI18N
        calcular.setForeground(new java.awt.Color(255, 102, 102));
        calcular.setText("Atualizar");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        getContentPane().add(calcular);
        calcular.setBounds(140, 180, 100, 35);

        disco.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        disco.setText("20%");
        getContentPane().add(disco);
        disco.setBounds(240, 110, 50, 32);

        cpu.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        cpu.setText("50%");
        getContentPane().add(cpu);
        cpu.setBounds(70, 110, 60, 32);

        memoria.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        memoria.setText("35%");
        getContentPane().add(memoria);
        memoria.setBounds(150, 110, 70, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
                Random aleatorio1 = new Random();
                Random aleatorio2 = new Random();
                Random aleatorio3 = new Random();
                
                Integer num1, num2, num3;
                
                num1 = aleatorio1.nextInt(101);
                num2 = aleatorio1.nextInt(101);
                num3 = aleatorio1.nextInt(101);
                
                cpu.setText(String.valueOf(num1 + "%"));
                memoria.setText(String.valueOf(num2 + "%"));
                disco.setText(String.valueOf(num3 + "%"));
                
                
    }//GEN-LAST:event_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proj2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JLabel cpu;
    private javax.swing.JLabel disco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel memoria;
    // End of variables declaration//GEN-END:variables
}
