/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.singletec;

import java.awt.Color;

/**
 *
 * @author Matrix
 */
public class TelaFormaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form TelaFormaPagamento
     */
    public TelaFormaPagamento() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btn10 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn50 = new javax.swing.JButton();
        btn80 = new javax.swing.JButton();
        btn100 = new javax.swing.JButton();
        btnSaldo = new javax.swing.JButton();
        btnOutroValor = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(797, 438));
        setMinimumSize(new java.awt.Dimension(797, 438));
        setPreferredSize(new java.awt.Dimension(797, 438));
        getContentPane().setLayout(null);

        btn10.setBackground(new java.awt.Color(51, 51, 255));
        btn10.setForeground(new java.awt.Color(255, 255, 255));
        btn10.setText("R$ 10,00");
        btn10.setToolTipText("");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn10);
        btn10.setBounds(260, 60, 100, 30);

        btn20.setBackground(new java.awt.Color(51, 51, 255));
        btn20.setForeground(new java.awt.Color(255, 255, 255));
        btn20.setText("R$ 20,00");
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        getContentPane().add(btn20);
        btn20.setBounds(390, 60, 100, 30);

        btn30.setBackground(new java.awt.Color(255, 0, 0));
        btn30.setForeground(new java.awt.Color(255, 255, 255));
        btn30.setText("R$ 30,00");
        btn30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn30ActionPerformed(evt);
            }
        });
        getContentPane().add(btn30);
        btn30.setBounds(510, 60, 100, 30);

        btn50.setBackground(new java.awt.Color(255, 102, 0));
        btn50.setForeground(new java.awt.Color(255, 255, 255));
        btn50.setText("R$ 50,00");
        btn50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn50ActionPerformed(evt);
            }
        });
        getContentPane().add(btn50);
        btn50.setBounds(260, 120, 100, 30);

        btn80.setBackground(new java.awt.Color(204, 102, 0));
        btn80.setForeground(new java.awt.Color(255, 255, 255));
        btn80.setText(" R$ 80,00");
        btn80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn80ActionPerformed(evt);
            }
        });
        getContentPane().add(btn80);
        btn80.setBounds(390, 120, 100, 30);

        btn100.setBackground(new java.awt.Color(153, 153, 255));
        btn100.setForeground(new java.awt.Color(255, 255, 255));
        btn100.setText("R$ 100,00");
        btn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100ActionPerformed(evt);
            }
        });
        getContentPane().add(btn100);
        btn100.setBounds(510, 120, 100, 30);

        btnSaldo.setBackground(new java.awt.Color(204, 204, 204));
        btnSaldo.setText("Saldo Atual  R$ 10,00");
        btnSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaldo);
        btnSaldo.setBounds(220, 180, 140, 30);

        btnOutroValor.setBackground(new java.awt.Color(0, 51, 204));
        btnOutroValor.setForeground(new java.awt.Color(255, 255, 255));
        btnOutroValor.setText("Outro Valor");
        btnOutroValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutroValorActionPerformed(evt);
            }
        });
        getContentPane().add(btnOutroValor);
        btnOutroValor.setBounds(520, 180, 100, 30);

        btnCancelar.setBackground(new java.awt.Color(153, 153, 153));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(200, 240, 90, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Min R$ 0,00");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 260, 83, 10);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Recarga Selecionada");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 350, 150, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Comum");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(530, 350, 58, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("AJUDA 24H LIGUE GRÁTIS 0800 648 2040 ATM-GUI-01  ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 410, 400, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Qual o valor desejado?");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 20, 200, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn30ActionPerformed

    }//GEN-LAST:event_btn30ActionPerformed

    private void btn50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn50ActionPerformed

    private void btn80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn80ActionPerformed

    private void btn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn100ActionPerformed

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaldoActionPerformed

    private void btnOutroValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutroValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOutroValorActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFormaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn100;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn50;
    private javax.swing.JButton btn80;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOutroValor;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
