/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.singletec;

/**
 *
 * @author bella
 */
public class TelaRecarga extends javax.swing.JFrame {

    /**
     * Creates new form TelaJFrame
     */
    public TelaRecarga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BtnReembolso = new javax.swing.JButton();
        BtnReembolso1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(785, 441));
        getContentPane().setLayout(null);

        BtnReembolso.setBackground(new java.awt.Color(0, 153, 153));
        BtnReembolso.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        BtnReembolso.setForeground(new java.awt.Color(255, 255, 255));
        BtnReembolso.setText("REEMBOLSO");
        BtnReembolso.setAutoscrolls(true);
        getContentPane().add(BtnReembolso);
        BtnReembolso.setBounds(550, 330, 170, 51);

        BtnReembolso1.setBackground(new java.awt.Color(102, 102, 102));
        BtnReembolso1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        BtnReembolso1.setForeground(new java.awt.Color(255, 255, 255));
        BtnReembolso1.setText("CANCELA");
        BtnReembolso1.setAutoscrolls(true);
        getContentPane().add(BtnReembolso1);
        BtnReembolso1.setBounds(30, 330, 170, 51);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\bella\\OneDrive\\Área de Trabalho\\Bilhete-unico\\Devops\\Java\\singletec\\src\\main\\java\\com\\mycompany\\singletec\\myimageapp\\Svt.PNG")); // NOI18N
        jLabel1.setText("10");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(480, 240, 150, 40);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setText("Qual a recarga desejada?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 10, 330, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\bella\\OneDrive\\Área de Trabalho\\Bilhete-unico\\Devops\\Java\\singletec\\src\\main\\java\\com\\mycompany\\singletec\\myimageapp\\trabArroba.PNG")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 80, 147, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\bella\\OneDrive\\Área de Trabalho\\Bilhete-unico\\Devops\\Java\\singletec\\src\\main\\java\\com\\mycompany\\singletec\\myimageapp\\estudIcon.PNG")); // NOI18N
        jLabel5.setText("jLabel3");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 80, 160, 100);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\bella\\OneDrive\\Área de Trabalho\\Bilhete-unico\\Devops\\Java\\singletec\\src\\main\\java\\com\\mycompany\\singletec\\myimageapp\\tempIcon.PNG")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(600, 80, 150, 100);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\bella\\OneDrive\\Área de Trabalho\\Bilhete-unico\\Devops\\Java\\singletec\\src\\main\\java\\com\\mycompany\\singletec\\myimageapp\\pessoasicon.PNG")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 80, 130, 100);

        jButton5.setBackground(new java.awt.Color(229, 36, 10));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("COMUM");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(30, 180, 130, 30);

        jButton6.setBackground(new java.awt.Color(255, 204, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("TEMPORÁRIA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(600, 180, 150, 30);

        jButton7.setBackground(new java.awt.Color(0, 102, 204));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("VALE TRANSPORTE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(420, 180, 150, 30);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel10.setText("10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(110, 250, 50, 20);

        jButton9.setBackground(new java.awt.Color(0, 153, 255));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("ESTUDANTE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(210, 180, 160, 30);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel11.setText("Nº Cartão 0745505218");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 20, 170, 20);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\bella\\OneDrive\\Área de Trabalho\\Bilhete-unico\\Devops\\Java\\singletec\\src\\main\\java\\com\\mycompany\\singletec\\myimageapp\\Svc.PNG")); // NOI18N
        jLabel12.setText("10");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 240, 160, 40);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\bella\\OneDrive\\Área de Trabalho\\Bilhete-unico\\Devops\\Java\\singletec\\src\\main\\java\\com\\mycompany\\singletec\\myimageapp\\Sve.PNG")); // NOI18N
        jLabel13.setText("10");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(250, 240, 160, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRecarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnReembolso;
    private javax.swing.JButton BtnReembolso1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
